---
title: "spammR: Spatial Analysis of Multiomics Measurements in R"
author:
- name: Harkirat Sohi
  affiliation: Pacific Northwest National Laboratory
- name: Sara Gosline
  affiliation: Pacific Northwest National Laboratory
  email: sara.gosline@pnnl.gov
package: spammR
output:
  BiocStyle::html_document
abstract: |
  A basic walkthrough of how to use and analyzie spatial multiomics measurements in the spammR package
vignette: |
  %\VignetteIndexEntry{spammR}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

# Getting started

To install the package currently you must install directly from `GitHub` along with the leapR dependency as shown below.
```
library(devtools)
devtools::install_github('PNNL-CompBio/leapR')
devtools::install_github('PNNL-CompBio/spammR')
```

Once the package is installed you can begin to evaluate the functionality. 

# Pancreatic spatial proteomic measurements

To evaluate the features of this package we are using pancreatic data from [Gosline et al.]() that is captured using mass spectrometry measused from 7 independent regions of a single human pancreas. Each image is segemented into nine 'voxels', with one voxel per image representing a cluster of islet cells. 

# Loading data into SpatialExperiment object

We first include functionality to load the data into a `SpatialExperiment` object. 



# Differential Expression

# Distance based measurements



# Equations

To number and reference equations, put them in equation environments and assign labels to them, see Equation \@ref(eq:binom).

\begin{equation}
  f\left(k\right) = \binom{n}{k} p^k\left(1-p\right)^{n-k}
  (\#eq:binom)
\end{equation}


# Tables

Like figures, tables with captions will also be numbered and can be referenced, see Table \@ref(tab:table).

Fruit   | Price
------- | -----
bananas | 1.2
apples  | 1.0
oranges | 2.5

: (\#tab:table) A simple table. With caption.


# Cross-references

Apart from referencing figures (Section \@ref(figures)), tables (Section \@ref(tables)), and equations (Section \@ref(equations)), you can also use the same syntax to refer to sections by their default labels generated by pandoc.


# Side notes

Footnotes are displayed as side notes on the right margin^[this is a side note entered as a footnote], which has the advantage that they appear close to the place where they are defined.

# References {.unnumbered}

1. Gosline et al.
2. Spatial Experiment

# Session info

```{r sessionInfo, echo=FALSE}
sessionInfo()
```
